name: Fly Deploy
on:
    push:
        branches:
            - master
        paths-ignore:
            - .github/**
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}

jobs:
    deploy:
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            # - name: Harden Runner
            #   uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
            #   with:
            #     disable-sudo: true
            #     egress-policy: audit

            - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
            - uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # v1.5
            - run: flyctl deploy --remote-only
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
